version: "3.9"

services:
  postgres:
    image: ankane/pgvector:latest  # Postgres with pgvector extension pre-installed
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vector_store
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5.18
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4JLABS_PLUGINS: '["graph-data-science"]'
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    volumes:
      - neo4jdata:/data

  api:
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8765
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: vector_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password
    depends_on:
      - postgres
      - neo4j
    ports:
      - "8765:8765"

  ui:
    build: ./ui
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8765
    depends_on:
      - api
    ports:
      - "3010:3000"

volumes:
  pgdata:
  neo4jdata: 