---
# Dashy Configuration - Fixed Network Connectivity
pageInfo:
  title: DrJ Labs Dashboard
  description: Self-hosted services dashboard with proper network routing
  logo: https://i.ibb.co/qWWpD0v/astro-dab-128.png
  
# App configuration
appConfig:
  theme: night
  layout: auto
  iconSize: large
  language: en
  startingView: default
  defaultOpeningMethod: sametab
  statusCheck: true
  statusCheckInterval: 300
  webSearch:
    disableWebSearch: false
    searchEngine: duckduckgo
  enableMultiTasking: true
  
  # Network-aware configuration
  allowConfigEdit: true
  enableServiceWorker: true
  disableSmartSort: false
  disableUpdateChecks: false
  hideErrors: false

sections:
- name: Container Management
  icon: fas fa-server
  items:
  - title: Portainer Web UI
    description: Container management - HTTPS interface
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/portainer.svg
    url: https://localhost:9443
    target: newtab
    statusCheck: true
    statusCheckUrl: http://172.22.0.6:9443
    statusCheckAcceptCodes: "200,300,301,302,403,404"
    
  - title: Portainer (Host Access)
    description: Direct host access to Portainer
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/portainer.svg
    url: https://localhost:9443
    target: newtab
    statusCheck: false

- name: Development & Monitoring
  icon: fas fa-code
  items:
  - title: Memory Dashboard
    description: Mem0 OpenMemory Dashboard
    icon: fas fa-brain
    url: http://localhost:3010
    target: sametab
    statusCheck: true
    statusCheckUrl: http://172.22.0.1:3010
    
  - title: Memory API
    description: Memory system API endpoint
    icon: fas fa-database
    url: http://localhost:8765/docs
    target: newtab
    statusCheck: true
    statusCheckUrl: http://172.22.0.1:8765
    
  - title: Qdrant Vector DB
    description: Vector database interface
    icon: fas fa-vector-square
    url: http://localhost:6333/dashboard
    target: sametab
    statusCheck: true
    statusCheckUrl: http://172.22.0.1:6333
    
  - title: Working Memory Dashboard
    description: Alternative memory dashboard
    icon: fas fa-memory
    url: http://localhost:8082
    target: sametab
    statusCheck: true
    statusCheckUrl: http://172.22.0.1:8082

- name: Network Diagnostics
  icon: fas fa-network-wired
  items:
  - title: Portainer (Container IP)
    description: Direct container access for testing
    icon: fas fa-server
    url: http://172.22.0.6:9443
    target: newtab
    statusCheck: true
    statusCheckAcceptCodes: "200,300,301,302,403,404,500"
    
  - title: Gateway Access
    description: Network gateway for troubleshooting
    icon: fas fa-gateway
    url: http://172.22.0.1
    target: newtab
    statusCheck: true
    statusCheckAcceptCodes: "200,300,301,302,403,404,500"

- name: System Utilities
  icon: fas fa-tools
  items:
  - title: System Monitor
    description: Local system monitoring (if available)
    icon: fas fa-chart-line
    url: http://localhost:19999
    target: sametab
    statusCheck: false
    
  - title: Traefik Dashboard
    description: Reverse proxy dashboard
    icon: fas fa-route
    url: http://localhost:8080
    target: sametab
    statusCheck: false

- name: Quick Links
  icon: fas fa-external-link-alt
  items:
  - title: GitHub
    description: Source code repositories
    icon: fab fa-github
    url: https://github.com
    target: newtab
    
  - title: Docker Hub
    description: Container registry
    icon: fab fa-docker
    url: https://hub.docker.com
    target: newtab
    
  - title: Localhost Root
    description: Local development root
    icon: fas fa-home
    url: http://localhost
    target: newtab 