---
# Dashy Configuration - Self-Hosted Dashboard
pageInfo:
  title: DrJ Labs Dashboard
  description: Self-hosted services dashboard
  logo: https://i.ibb.co/qWWpD0v/astro-dab-128.png
  
# App configuration
appConfig:
  theme: night
  layout: auto
  iconSize: large
  language: en
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: true
  statusCheckInterval: 300
  webSearch:
    disableWebSearch: false
    searchEngine: duckduckgo
  enableMultiTasking: true
  
  # Security and CORS handling
  allowConfigEdit: true
  enableServiceWorker: true
  disableSmartSort: false
  disableUpdateChecks: false
  hideErrors: false
  
  # Fix iframe and embedding issues
  enableErrorReporting: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false

sections:
- name: Container Management
  icon: fas fa-server
  items:
  - title: Portainer (HTTPS)
    description: Container management interface
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/portainer.svg
    url: https://localhost:9443
    target: newtab
    statusCheck: false
    
  - title: Portainer (HTTP)
    description: Container management - HTTP fallback
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/portainer.svg
    url: http://localhost:8000
    target: newtab
    statusCheck: false

- name: Development & Monitoring
  icon: fas fa-code
  items:
  - title: Memory System
    description: Mem0 OpenMemory Dashboard
    icon: fas fa-brain
    url: http://localhost:3010
    target: newtab
    statusCheck: true
    
  - title: Memory API
    description: Memory system API endpoint
    icon: fas fa-database
    url: http://localhost:8765
    target: newtab
    statusCheck: true
    
  - title: Qdrant Vector DB
    description: Vector database interface
    icon: fas fa-vector-square
    url: http://localhost:6333
    target: newtab
    statusCheck: true

- name: System Utilities
  icon: fas fa-tools
  items:
  - title: System Monitor
    description: Local system monitoring
    icon: fas fa-chart-line
    url: http://localhost:19999
    target: newtab
    statusCheck: false
    
  - title: Docker Stats
    description: Container statistics
    icon: fab fa-docker
    url: http://localhost:9000
    target: newtab
    statusCheck: false

- name: Quick Links
  icon: fas fa-external-link-alt
  items:
  - title: GitHub
    description: Source code repositories
    icon: fab fa-github
    url: https://github.com
    target: newtab
    
  - title: Docker Hub
    description: Container registry
    icon: fab fa-docker
    url: https://hub.docker.com
    target: newtab
    
  - title: Localhost
    description: Local development
    icon: fas fa-home
    url: http://localhost
    target: newtab 