---
# Dashy Configuration - Self-Hosted Dashboard (Updated with Proxies)
pageInfo:
  title: DrJ Labs Dashboard
  description: Self-hosted services dashboard with seamless integration
  logo: https://i.ibb.co/qWWpD0v/astro-dab-128.png
  
# App configuration
appConfig:
  theme: night
  layout: auto
  iconSize: large
  language: en
  startingView: default
  defaultOpeningMethod: sametab
  statusCheck: true
  statusCheckInterval: 300
  webSearch:
    disableWebSearch: false
    searchEngine: duckduckgo
  enableMultiTasking: true
  
  # Security and CORS handling
  allowConfigEdit: true
  enableServiceWorker: true
  disableSmartSort: false
  disableUpdateChecks: false
  hideErrors: false
  
  # Enhanced iframe and embedding support
  enableErrorReporting: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false

sections:
- name: Container Management
  icon: fas fa-server
  items:
  - title: Portainer (Proxied)
    description: Container management via proxy - no security errors
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/portainer.svg
    url: http://localhost:9080
    target: sametab
    statusCheck: true
    
  - title: Portainer (Direct HTTPS)
    description: Direct HTTPS access - may show security warnings
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/portainer.svg
    url: https://localhost:9443
    target: newtab
    statusCheck: false
    
  - title: Portainer (Direct HTTP)
    description: Direct HTTP access to edge agent
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/portainer.svg
    url: http://localhost:8000
    target: newtab
    statusCheck: true

- name: Development & Monitoring
  icon: fas fa-code
  items:
  - title: Memory Dashboard
    description: Mem0 OpenMemory Dashboard
    icon: fas fa-brain
    url: http://localhost:3010
    target: sametab
    statusCheck: true
    
  - title: Memory API
    description: Memory system API endpoint
    icon: fas fa-database
    url: http://localhost:8765/docs
    target: newtab
    statusCheck: true
    
  - title: Qdrant Vector DB
    description: Vector database interface
    icon: fas fa-vector-square
    url: http://localhost:6333/dashboard
    target: sametab
    statusCheck: true
    
  - title: Working Memory Dashboard
    description: Alternative memory dashboard
    icon: fas fa-memory
    url: http://localhost:8082
    target: sametab
    statusCheck: true

- name: System Utilities
  icon: fas fa-tools
  items:
  - title: System Monitor
    description: Local system monitoring (if available)
    icon: fas fa-chart-line
    url: http://localhost:19999
    target: sametab
    statusCheck: false
    
  - title: Docker Stats
    description: Container statistics (if available)
    icon: fab fa-docker
    url: http://localhost:9000
    target: sametab
    statusCheck: false
    
  - title: Traefik Dashboard
    description: Reverse proxy dashboard (if available)
    icon: fas fa-route
    url: http://localhost:8080
    target: sametab
    statusCheck: false

- name: Quick Links
  icon: fas fa-external-link-alt
  items:
  - title: GitHub
    description: Source code repositories
    icon: fab fa-github
    url: https://github.com
    target: newtab
    
  - title: Docker Hub
    description: Container registry
    icon: fab fa-docker
    url: https://hub.docker.com
    target: newtab
    
  - title: Localhost Root
    description: Local development root
    icon: fas fa-home
    url: http://localhost
    target: newtab

- name: Configuration
  icon: fas fa-cog
  items:
  - title: Dashy Settings
    description: Configure this dashboard
    icon: fas fa-cogs
    url: http://localhost:4000
    target: sametab
    
  - title: Reload Configuration
    description: Refresh dashboard config
    icon: fas fa-sync-alt
    url: http://localhost:4000/?refresh=true
    target: sametab 