version: "3.8"

services:
  mem0_store:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - mem0_storage:/qdrant/storage

  openmemory-mcp:
    image: mem0/openmemory-mcp:latest
    depends_on:
      - mem0_store
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:?set your OPENAI_API_KEY}
      - USER=${USER:-mem0}
      - QDRANT_HOST=mem0_store
      - QDRANT_PORT=6333
    ports:
      - "8765:8765"

  openmemory-ui:
    image: mem0/openmemory-ui:latest
    depends_on:
      - openmemory-mcp
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8765
      - NEXT_PUBLIC_USER_ID=${USER:-mem0}
    ports:
      - "3000:3000"

volumes:
  mem0_storage:
    driver: local