version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: memorybank-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: memorybank-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ../monitoring/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json:ro
      - ../monitoring/dependency-metrics-dashboard.json:/etc/grafana/provisioning/dashboards/dependency-metrics-dashboard.json:ro
      - ./grafana-dashboard-provisioning.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - ./grafana-datasource-provisioning.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
    depends_on:
      - prometheus
    networks:
      - monitoring

  dependency-metrics-exporter:
    build:
      context: ..
      dockerfile: docker/Dockerfile.metrics-exporter
    container_name: memorybank-metrics-exporter
    environment:
      - METRICS_PORT=9091
    ports:
      - "9091:9091"
    volumes:
      - ../:/app:ro
    networks:
      - monitoring
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge 