version: '3.8'

services:
  postgres-test:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: memorybank_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_preload_libraries=vector
      -c log_statement=all
      -c log_destination=stderr
      -c logging_collector=off
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d memorybank_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data: 