# Traefik TLS 1.3 Configuration
# Place this in /etc/traefik/dynamic/tls-options.yml

tls:
  options:
    # Modern TLS configuration (TLS 1.2 + 1.3 only)
    modern:
      minVersion: VersionTLS12
      maxVersion: VersionTLS13
      cipherSuites:
        # TLS 1.3 cipher suites (automatically used when TLS 1.3 is negotiated)
        # These are implicit and don't need to be specified
        
        # TLS 1.2 cipher suites (only the most secure)
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - X25519
        - P-256
        - P-384
      sniStrict: true
    
    # Ultra-modern configuration (TLS 1.3 only)
    tls13only:
      minVersion: VersionTLS13
      maxVersion: VersionTLS13
      sniStrict: true
    
    # Default configuration (currently in use)
    default:
      minVersion: VersionTLS12
      sniStrict: true

  stores:
    default:
      defaultGeneratedCert:
        resolver: cloudflare
        domain:
          main: "drjlabs.com"
          sans:
            - "*.drjlabs.com" 